export const mockItems = [
    {
      id: 123456789,
      node_id: "MDEwOlJlcG9zaXRvcnkxMjM0NTY3OA==",
      name: "repo-name",
      full_name: "username/repo-name",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/repo-name",
      description: "A short description of the repository.",
      fork: false,
      url: "https://api.github.com/repos/username/repo-name",
      created_at: "2023-01-01T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 50,
      watchers_count: 50,
      language: "Python",
      forks_count: 10,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 0,
      default_branch: "main",
    },
    {
      id: 987654321,
      node_id: "MDEwOlJlcG9zaXRvcnk5ODc2NTQzMg==",
      name: "another-repo",
      full_name: "username/another-repo",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/another-repo",
      description: "Another repository description.",
      fork: false,
      url: "https://api.github.com/repos/username/another-repo",
      created_at: "2023-01-15T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 20,
      watchers_count: 20,
      language: "JavaScript",
      forks_count: 5,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 1,
      default_branch: "main",
    },
    {
      id: 123456789,
      node_id: "MDEwOlJlcG9zaXRvcnkxMjM0NTY3OA==",
      name: "repo-name",
      full_name: "username/repo-name",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/repo-name",
      description: "A short description of the repository.",
      fork: false,
      url: "https://api.github.com/repos/username/repo-name",
      created_at: "2023-01-01T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 50,
      watchers_count: 50,
      language: "Python",
      forks_count: 10,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 0,
      default_branch: "main",
    },
    {
      id: 987654321,
      node_id: "MDEwOlJlcG9zaXRvcnk5ODc2NTQzMg==",
      name: "another-repo",
      full_name: "username/another-repo",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/another-repo",
      description: "Another repository description.",
      fork: false,
      url: "https://api.github.com/repos/username/another-repo",
      created_at: "2023-01-15T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 20,
      watchers_count: 20,
      language: "JavaScript",
      forks_count: 5,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 1,
      default_branch: "main",
    },
    {
      id: 123456789,
      node_id: "MDEwOlJlcG9zaXRvcnkxMjM0NTY3OA==",
      name: "repo-name",
      full_name: "username/repo-name",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/repo-name",
      description: "A short description of the repository.",
      fork: false,
      url: "https://api.github.com/repos/username/repo-name",
      created_at: "2023-01-01T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 50,
      watchers_count: 50,
      language: "Python",
      forks_count: 10,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 0,
      default_branch: "main",
    },
    {
      id: 987654321,
      node_id: "MDEwOlJlcG9zaXRvcnk5ODc2NTQzMg==",
      name: "another-repo",
      full_name: "username/another-repo",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/another-repo",
      description: "Another repository description.",
      fork: false,
      url: "https://api.github.com/repos/username/another-repo",
      created_at: "2023-01-15T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 20,
      watchers_count: 20,
      language: "JavaScript",
      forks_count: 5,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 1,
      default_branch: "main",
    },
    {
      id: 123456789,
      node_id: "MDEwOlJlcG9zaXRvcnkxMjM0NTY3OA==",
      name: "repo-name",
      full_name: "username/repo-name",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/repo-name",
      description: "A short description of the repository.",
      fork: false,
      url: "https://api.github.com/repos/username/repo-name",
      created_at: "2023-01-01T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 50,
      watchers_count: 50,
      language: "Python",
      forks_count: 10,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 0,
      default_branch: "main",
    },
    {
      id: 987654321,
      node_id: "MDEwOlJlcG9zaXRvcnk5ODc2NTQzMg==",
      name: "another-repo",
      full_name: "username/another-repo",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/another-repo",
      description: "Another repository description.",
      fork: false,
      url: "https://api.github.com/repos/username/another-repo",
      created_at: "2023-01-15T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 20,
      watchers_count: 20,
      language: "JavaScript",
      forks_count: 5,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 1,
      default_branch: "main",
    },
    {
      id: 123456789,
      node_id: "MDEwOlJlcG9zaXRvcnkxMjM0NTY3OA==",
      name: "repo-name",
      full_name: "username/repo-name",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/repo-name",
      description: "A short description of the repository.",
      fork: false,
      url: "https://api.github.com/repos/username/repo-name",
      created_at: "2023-01-01T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 50,
      watchers_count: 50,
      language: "Python",
      forks_count: 10,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 0,
      default_branch: "main",
    },
    {
      id: 987654321,
      node_id: "MDEwOlJlcG9zaXRvcnk5ODc2NTQzMg==",
      name: "another-repo",
      full_name: "username/another-repo",
      private: false,
      owner: {
        login: "username",
        id: 12345,
        node_id: "MDQ6VXNlcjEyMzQ1",
        avatar_url: "https://avatars.githubusercontent.com/u/12345?v=4",
        html_url: "https://github.com/username",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/username/another-repo",
      description: "Another repository description.",
      fork: false,
      url: "https://api.github.com/repos/username/another-repo",
      created_at: "2023-01-15T00:00:00Z",
      updated_at: "2023-02-01T00:00:00Z",
      pushed_at: "2023-02-01T00:00:00Z",
      stargazers_count: 20,
      watchers_count: 20,
      language: "JavaScript",
      forks_count: 5,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
      },
      open_issues_count: 1,
      default_branch: "main",
    },
  ];